# -*- coding: utf-8 -*-
"""berttest

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GihTKDQprvpgyK14p3W_mW1KHLEN7rb0


"""# Import Packages"""

import numpy as np
import random
import torch
from torch.utils.data import DataLoader, Dataset 
from transformers import AdamW, BertForQuestionAnswering, BertTokenizerFast, BertForSequenceClassification
from tqdm.auto import tqdm
import pandas as pd
from torch.nn.utils.rnn import pad_sequence
import os

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print("device:", device)
# Fix random seed for reproducibility
def same_seeds(seed):
	  torch.manual_seed(seed)
	  if torch.cuda.is_available():
		    torch.cuda.manual_seed(seed)
		    torch.cuda.manual_seed_all(seed)
	  np.random.seed(seed)
	  random.seed(seed)
	  torch.backends.cudnn.benchmark = False
	  torch.backends.cudnn.deterministic = True

same_seeds(0)

"""# Load Model and Tokenizer"""

tokenizer = BertTokenizerFast.from_pretrained("bert-base-chinese")

"""# Add Token"""

##godjj
#改為for迴圈自訂貼圖
tokenizer.add_tokens(["corgi4"],special_tokens=True)
tokenizer.add_tokens(["corgiAA"],special_tokens=True)
tokenizer.add_tokens(["corgiAgain"],special_tokens=True)
tokenizer.add_tokens(["corgiAyaya"],special_tokens=True)
tokenizer.add_tokens(["corgiBK"],special_tokens=True)
tokenizer.add_tokens(["corgiBlue"],special_tokens=True)
tokenizer.add_tokens(["corgiCry"],special_tokens=True)
tokenizer.add_tokens(["corgiD"],special_tokens=True)
tokenizer.add_tokens(["corgiDinoHi"],special_tokens=True)
tokenizer.add_tokens(["corgiDinoTired"],special_tokens=True)
tokenizer.add_tokens(["corgiE"],special_tokens=True)
tokenizer.add_tokens(["corgiGF0"],special_tokens=True)
tokenizer.add_tokens(["corgiGF1"],special_tokens=True)
tokenizer.add_tokens(["corgiGG"],special_tokens=True)
tokenizer.add_tokens(["corgiGoDJJ"],special_tokens=True)
tokenizer.add_tokens(["corgiGrandMa"],special_tokens=True)
tokenizer.add_tokens(["corgiGreedy"],special_tokens=True)
tokenizer.add_tokens(["corgiHE"],special_tokens=True)
tokenizer.add_tokens(["corgiHEY"],special_tokens=True)
tokenizer.add_tokens(["corgiHIT"],special_tokens=True)
tokenizer.add_tokens(["corgiJ"],special_tokens=True)
tokenizer.add_tokens(["corgiJJJ"],special_tokens=True)
tokenizer.add_tokens(["corgiJJJJ"],special_tokens=True)
tokenizer.add_tokens(["corgiJPOP"],special_tokens=True)
tokenizer.add_tokens(["corgiLuL"],special_tokens=True)
tokenizer.add_tokens(["corgiMonkey1"],special_tokens=True)
tokenizer.add_tokens(["corgiMonkey2"],special_tokens=True)
tokenizer.add_tokens(["corgiNicE"],special_tokens=True)
tokenizer.add_tokens(["corgiNo"],special_tokens=True)
tokenizer.add_tokens(["corgiNoneed"],special_tokens=True)
tokenizer.add_tokens(["corgiOK"],special_tokens=True)
tokenizer.add_tokens(["corgiPink"],special_tokens=True)
tokenizer.add_tokens(["corgiPlusOne"],special_tokens=True)
tokenizer.add_tokens(["corgiPoor"],special_tokens=True)
tokenizer.add_tokens(["corgiQ"],special_tokens=True)
tokenizer.add_tokens(["corgiQQ"],special_tokens=True)
tokenizer.add_tokens(["corgiQualifieD"],special_tokens=True)
tokenizer.add_tokens(["corgiR"],special_tokens=True)
tokenizer.add_tokens(["corgiRD"],special_tokens=True)
tokenizer.add_tokens(["corgiRO"],special_tokens=True)
tokenizer.add_tokens(["corgiRR"],special_tokens=True)
tokenizer.add_tokens(["corgiSleeper"],special_tokens=True)
tokenizer.add_tokens(["corgiSongLa"],special_tokens=True)
tokenizer.add_tokens(["corgiUmm"],special_tokens=True)
tokenizer.add_tokens(["corgiWhat"],special_tokens=True)
tokenizer.add_tokens(["corgiF"],special_tokens=True)
tokenizer.add_tokens(["corgiFAIL"],special_tokens=True)
tokenizer.add_tokens(["corgiH1"],special_tokens=True)
tokenizer.add_tokens(["corgiM"],special_tokens=True)
tokenizer.add_tokens(["corgiW"],special_tokens=True)
tokenizer.add_tokens(["corgiGold"],special_tokens=True)
tokenizer.add_tokens(["corgiH4"],special_tokens=True)
tokenizer.add_tokens(["corgiHey"],special_tokens=True)
tokenizer.add_tokens(["corgiJJ"],special_tokens=True)
tokenizer.add_tokens(["corgiMoney"],special_tokens=True)
tokenizer.add_tokens(["corgiP2"],special_tokens=True)
tokenizer.add_tokens(["corgi30"],special_tokens=True)
tokenizer.add_tokens(["corgiP"],special_tokens=True)
tokenizer.add_tokens(["corgiS"],special_tokens=True)
tokenizer.add_tokens(["corgiT1"],special_tokens=True)
tokenizer.add_tokens(["corgiT2"],special_tokens=True)

"""#Read Data"""

godjj_trains=pd.read_csv("godjj_scored.csv")
godjj_trains.to_csv("godjj_scored.tsv", sep="\t", index=False)
#print(godjj_trains["data"])
filepath = "Chatmodel.pt"
"""# Tokenize Data

# Dataset and Dataloader
"""

class SentimentAnalysis_Dataset:
  def __init__(self, mode, tokenizer, DATASET):
    self.mode = mode
    self.tokenizer = tokenizer
    self.df = pd.read_csv(DATASET,sep="\t").fillna("")
    self.len = len(self.df)
    self.tokenizer = tokenizer
  
  def __getitem__(self,idx):
    if(self.mode == "train"):
      date, name, data, score = self.df.iloc[idx,:].values
      #print(score)
      if(score == ''):
        label_tensor = torch.tensor(1)
      else:
        label_tensor = torch.tensor(int(score)+1)
    else:
      date, name, data = self.df.iloc[idx,:].values
      label_tensor = None
    
    word_pieces = ["[CLS]"]
    tokena = self.tokenizer.tokenize(data)
    word_pieces += tokena + ["[SEP]"]
    ids = self.tokenizer.convert_tokens_to_ids(word_pieces)
    tokens_tensor = torch.tensor(ids)
    segments_tensor = torch.tensor([0]*len(word_pieces)) 
    return (tokens_tensor, segments_tensor, label_tensor)

  def __len__(self):
    return self.len

tokenizer = BertTokenizerFast.from_pretrained('bert-base-chinese')
trainset = SentimentAnalysis_Dataset("train", tokenizer=tokenizer,DATASET='godjj_scored.tsv')

'''sample_idx = 0
date,name,data,score = trainset.df.iloc[sample_idx].values
tokens_tensor, segments_tensor, label_tensor = trainset[sample_idx]
tokens = tokenizer.convert_ids_to_tokens(tokens_tensor.tolist())
print(data)
print(tokens_tensor)
print(segments_tensor)
print(label_tensor)'''

def create_mini_batch(samples):
  tokens_tensors = [s[0] for s in samples]
  segments_tensors = [s[1] for s in samples]
  if samples[0][2] is not None:
    label_ids = torch.stack([s[2] for s in samples])
  else:
    label_ids = None

  tokens_tensors = pad_sequence(tokens_tensors, batch_first=True)
  segments_tensors = pad_sequence(segments_tensors, batch_first=True)
  masks_tensors = torch.zeros(tokens_tensors.shape, dtype=torch.long)
  masks_tensors = masks_tensors.masked_fill(tokens_tensors != 0,1)
  return tokens_tensors, segments_tensors, masks_tensors, label_ids

BATCH_SIZE = 32
trainloader = DataLoader(trainset, batch_size=BATCH_SIZE, collate_fn=create_mini_batch)

data = next(iter(trainloader))

tokens_tensors, segments_tensors, masks_tensors, label_ids = data

'''print(f"""
tokens_tensors.shape   = {tokens_tensors.shape} 
{tokens_tensors}
------------------------
segments_tensors.shape = {segments_tensors.shape}
{segments_tensors}
------------------------
masks_tensors.shape    = {masks_tensors.shape}
{masks_tensors}
------------------------
label_ids.shape        = {label_ids.shape}
{label_ids}
""")'''

"""# Training"""

PRETRAINED_MODEL_NAME = "bert-base-chinese"
NUM_LABELS = 3
model = BertForSequenceClassification.from_pretrained(
    PRETRAINED_MODEL_NAME, num_labels=NUM_LABELS)

if os.path.exists(filepath):
    try:

        model.load_state_dict(torch.load(filepath))
        print("checkpoint loaded")
    
    except:

        os.remove(filepath)
        print("checkpoint deleted")

def get_predictions(model, dataloader, compute_acc=False):
    predictions = None
    correct = 0
    total = 0
      
    with torch.no_grad():
        # 遍巡整個資料集
        for data in dataloader:
            # 將所有 tensors 移到 GPU 上
            if next(model.parameters()).is_cuda:
                data = [t.to("cuda:0") for t in data if t is not None]
            
            
            # 別忘記前 3 個 tensors 分別為 tokens, segments 以及 masks
            # 且強烈建議在將這些 tensors 丟入 `model` 時指定對應的參數名稱
            tokens_tensors, segments_tensors, masks_tensors = data[:3]
            outputs = model(input_ids=tokens_tensors, 
                            token_type_ids=segments_tensors, 
                            attention_mask=masks_tensors)
            
            logits = outputs[0]
            _, pred = torch.max(logits.data, 1)
            
            # 用來計算訓練集的分類準確率
            if compute_acc:
                labels = data[3]
                total += labels.size(0)
                correct += (pred == labels).sum().item()
                
            # 將當前 batch 記錄下來
            if predictions is None:
                predictions = pred
            else:
                predictions = torch.cat((predictions, pred))
    
    if compute_acc:
        acc = correct / total
        return predictions, acc
    return predictions
    
# 讓模型跑在 GPU 上並取得訓練集的分類準確率
def train(model=model):
    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    print("device:", device)
    model = model.to(device)
    _, acc = get_predictions(model, trainloader, compute_acc=True)
    print("classification acc:", acc)
    
    """# Testing"""
    
    model.train()
    
    # 使用 Adam Optim 更新整個分類模型的參數
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-5)
    
    
    EPOCHS = 10  # 幸運數字
    for epoch in range(EPOCHS):
        
        running_loss = 0.0
        for data in trainloader:
            
            tokens_tensors, segments_tensors, \
            masks_tensors, labels = [t.to(device) for t in data]
    
            # 將參數梯度歸零
            optimizer.zero_grad()
            
            # forward pass
            outputs = model(input_ids=tokens_tensors, 
                            token_type_ids=segments_tensors, 
                            attention_mask=masks_tensors, 
                            labels=labels)
    
            loss = outputs[0]
            # backward
            loss.backward()
            optimizer.step()
    
    
            # 紀錄當前 batch loss
            running_loss += loss.item()
            
        # 計算分類準確率
        _, acc = get_predictions(model, trainloader, compute_acc=True)
    
        print('[epoch %d] loss: %.3f, acc: %.3f' %
              (epoch + 1, running_loss, acc))
    torch.save(model.state_dict(), filepath)
    torch.cuda.empty_cache()

if __name__ == '__main__':
    train()

